#r @"bin/Debug/net5.0/Akka.dll"
#r @"bin/Debug/net5.0/Akka.FSharp.dll"
#r @"bin/Debug/net5.0/MathNet.Numerics.dll"
#r @"bin/Debug/net5.0/MathNet.Numerics.FSharp.dll"
#r @"bin/Debug/net5.0/Suave.dll"
// #r @"bin/Debug/netcoreapp3.1/Akka.Remote.dll"
// #r @"bin/Debug/netcoreapp3.1/Akka.TestKit.dll"