#r @"bin/Debug/netcoreapp3.1/Akka.dll"
#r @"bin/Debug/netcoreapp3.1/Akka.FSharp.dll"
#r @"bin/Debug/netcoreapp3.1/MathNet.Numerics.dll"
#r @"bin/Debug/netcoreapp3.1/MathNet.Numerics.FSharp.dll"
// #r @"bin/Debug/netcoreapp3.1/Akka.Remote.dll"
// #r @"bin/Debug/netcoreapp3.1/Akka.TestKit.dll"